---
name: Scalar-Andand
version: 0.03
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Guarded method invocation.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Null: 0
  autobox::Core: 0
build_requires:
  Test::More: 0
provides:
  Scalar::Andand:
    file: lib/Scalar/Andand.pm
    version: 0.03
  Scalar::Andand::Undef:
    file: lib/Scalar/Andand.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
