---
name: Scalar-Andand
version: 0.04
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Guarded method invocation.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Null: 0
  autobox::Core: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
provides:
  Scalar::Andand:
    file: lib/Scalar/Andand.pm
    version: 0.04
  Scalar::Andand::Scalar:
    file: lib/Scalar/Andand/Scalar.pm
  Scalar::Andand::Undef:
    file: lib/Scalar/Andand/Undef.pm
    version: 0
no_index:
  package:
    - Scalar::Andand::Undef
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
